// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AccueilTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void accueilRecherchefructueuse() {
    // Test name: Accueil - Recherche fructueuse
    // Step # | name | target | value
    // 1 | open | /fruits/ | 
    driver.get("https://labasse.github.io/fruits/");
    // 2 | setWindowSize | 1280x720 | 
    driver.manage().window().setSize(new Dimension(1280, 720));
    // 3 | click | css=.form-control | 
    driver.findElement(By.cssSelector(".form-control")).click();
    // 4 | type | css=.form-control | ana
    driver.findElement(By.cssSelector(".form-control")).sendKeys("ana");
    // 5 | storeXpathCount | xpath=//div[contains(@class, "card ")] | cartes
    vars.put("cartes", driver.findElements(By.xpath("//div[contains(@class, \"card \")]")).size());
    // 6 | assert | cartes | 2
    assertEquals(vars.get("cartes").toString(), "2");
  }
  @Test
  public void accueilRechercheinfructueuse() {
    // Test name: Accueil - Recherche infructueuse
    // Step # | name | target | value
    // 1 | open | /fruits/ | 
    driver.get("https://labasse.github.io/fruits/");
    // 2 | setWindowSize | 1280x720 | 
    driver.manage().window().setSize(new Dimension(1280, 720));
    // 3 | click | css=.form-control | 
    driver.findElement(By.cssSelector(".form-control")).click();
    // 4 | type | css=.form-control | toto
    driver.findElement(By.cssSelector(".form-control")).sendKeys("toto");
    // 5 | assertElementNotPresent | css=.row-cols-1 > .col | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".row-cols-1 > .col"));
      assert(elements.size() == 0);
    }
  }
}
