# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Accueil' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'accueilRecherchefructueuse' do
    # Test name: Accueil - Recherche fructueuse
    # Step # | name | target | value
    # 1 | open | /fruits/ | 
    @driver.get('https://labasse.github.io/fruits/')
    # 2 | setWindowSize | 1280x720 | 
    @driver.manage.resize_to(1280, 720)
    # 3 | click | css=.form-control | 
    @driver.find_element(:css, '.form-control').click
    # 4 | type | css=.form-control | ana
    @driver.find_element(:css, '.form-control').send_keys('ana')
    # 5 | storeXpathCount | xpath=//div[contains(@class, "card ")] | cartes
    @vars['cartes'] = @driver.find_elements(:xpath, '//div[contains(@class, \"card \")]').length
    # 6 | assert | cartes | 2
    expect(@vars['cartes']).to eq(2)
  end
  it 'accueilRechercheinfructueuse' do
    # Test name: Accueil - Recherche infructueuse
    # Step # | name | target | value
    # 1 | open | /fruits/ | 
    @driver.get('https://labasse.github.io/fruits/')
    # 2 | setWindowSize | 1280x720 | 
    @driver.manage.resize_to(1280, 720)
    # 3 | click | css=.form-control | 
    @driver.find_element(:css, '.form-control').click
    # 4 | type | css=.form-control | toto
    @driver.find_element(:css, '.form-control').send_keys('toto')
    # 5 | assertElementNotPresent | css=.row-cols-1 > .col | 
    elements = @driver.find_elements(:css, '.row-cols-1 > .col')
    expect(elements.length).to eq(0)
  end
end
